### ISSUE TITLE
Where is chutzpah.runner.exe etc located

### ISSUE THREAD

**Issue by mwpowellhtx** [zpbappi/gulp-chutzpah#3]
I found where the Chutzpah extension is installed, but I cannot seem to locate where the runner executable is found. Can you point me in the right direction there? Thanks!

**Comment by zpbappi** [comment]
@mwpowellhtx my apologizes. The file name is `chutzpah.console.exe` and it is located in the root folder of Chutzpah distribution. I will fix the file name in the README file ASAP.

I will leave the issue open for now and will close once I have fixed the file name everywhere. Thanks for pointing it out.

**Comment by mwpowellhtx** [comment]
@zpbappi  To be honest, I'm not sure what you mean by *"root folder of Chutzpah distribution"*. I download a couple of things that I know of; one is the *Chutzpah VS extension*, which installs via the *Extensions* features; but which this is orchestrated by VS, nothing that I personally touch, per se.  Anything else is *Chutzpah* integration with components such as *Gulp*?

**Comment by mwpowellhtx** [comment]
@zpbappi Unless possibly we're talking about a project level *Chutzpah* [NuGet dependency](http://www.nuget.org/packages/Chutzpah). However, this is not clear from all the other docs that I've read about it; i.e. that there is a *VISX VS extension*.

**Comment by mwpowellhtx** [comment]
Added the NuGet dependency to the project. That did the trick, as far as test ubiquity is concerned, whether from Gulp-Chutzpah, or from the VS Test Runner.

Which now in retrospect, makes sense; there is the Test Runner Adapter, and then there is the runner itself. Although I think it is a little bit different for packages such as xUnit, just FYI. I believe that is a single dependency, not the Test Runner Adapter, per se. And gauging from some of the assemblies involved, perhaps there is some overlap there? I don't know exactly; VS add ins aren't my thing, per se, except in limited cases.

Which has also exposed a NuGet issue completely deleting my locally published packages to my chagrin. Ugh. But the Chutzpah was installed. Not sure why it wasn't installed local to the SOLUTION, however.

**Comment by zpbappi** [comment]
@mwpowellhtx I did not really run it from VS. I always ran it as a gulp task from non-VS environments. Mostly from command prompt, VS Code or in CI servers. You can possibly try to add the gulp task in VS (depending on your VS version, you may need to install the gulp task runner plugin for VS) to run post/pre-build events or whenever you want. And, yes, it is very different than xUnit and NUnit as they are .NET test frameworks. This is for javascript. 

If you are using the Chutzpah test runner plugin for VS, that is a completely different story. That plugin is to help you run tests in your VS environment. Whereas chutzpah (which you install either externally or using NuGet) is built to enable you to run tests in any environment. When you install chutzpah, it will definitely have a file `chutzpah.console.exe` in the installation directory. Because this file is what actually runs the tests. And, the `gulp-chutzpah` plugin simply helps you to use chutzpah from gulp.

**Comment by mwpowellhtx** [comment]
> I did not really run it from VS. I always ran it as a gulp task from non-VS environments. Mostly from command prompt, VS Code or in CI servers. You can possibly try to add the gulp task in VS (depending on your VS version, you may need to install the gulp task runner plugin for VS) to run post/pre-build events or whenever you want.

That is an important distinction. So the *Adapter* is "nothing more" than a bridge from the JavaScript environment to the IDE?

> And, yes, it is very different than xUnit and NUnit as they are .NET test frameworks. This is for javascript.

Got it; I get that, thank you. Just trying to sort out which guzintas and guzoutas (inputs and outputs) are in play here is all.

> If you are using the Chutzpah test runner plugin for VS, that is a completely different story. That plugin is to help you run tests in your VS environment. Whereas chutzpah (which you install either externally or using NuGet) is built to enable you to run tests in any environment. When you install chutzpah, it will definitely have a file chutzpah.console.exe in the installation directory. Because this file is what actually runs the tests. And, the gulp-chutzpah plugin simply helps you to use chutzpah from gulp.

Thanks for the clarification. :+1:
