### ISSUE TITLE
Command line too long

### ISSUE THREAD

**Issue by irega** [zpbappi/gulp-chutzpah#4]
Hi! We are using this plugin in our deploy process, but we have a large number of tests and when we execute them with the normal parameters, the console shows the "command line too long" error.

**Comment by zpbappi** [comment]
@irega I saw your pull requests. However, I would like to discuss few things related to the settings file here. 

I see the dilemma of having the settings file. If you have a settings file to specify your test files, then what do you select as a source stream using `gulp.src`. On the other hand, you did some modification that will enable this plugin to be used without creating any stream first (i.e. using `gulp.src`). In that case, why do you even need gulp? Why not simply write few lines of nodejs code that will execute the chutzpah runner using the settings file (which, you know the location of). 

Having said that, I think the inclusion of a settings file will be a valuable addition. However, I would like to propose a different way. That is, you create the stream using settings file(s). When you pipe the stream to this plugin, an option `isSettingsFile` (to be added) must be set to true. Let me know what do you think about this approach.

And, finally, in your pull requests, please do not include white space and new line additions- as they make it difficult to review. Almost all the lines will be changed just because of a whitespace. 

Thank you for your effort. I hope we can finish what you started. :)

**Comment by irega** [comment]
Totally agree with your approach, I have implemented it and updated the pull request. You're right, I can run the process with some code lines of nodejs but I prefer extend and use the plugin because it has more logic already done (like the generate string args process).

Please, let me know if the white spaces and end lines are correct, I am using "Visual studio Code" with Ubuntu and I believe that it adds them, what IDE are you using?

Greetings from Spain! ;)

**Comment by zpbappi** [comment]
@irega I use VS Code as well. We may have different linting options. Anyway, your PR looks good. However, I am concerned about existing functionality and tests. I would like to run thorough tests in a feature branch first before merging to master. I also need to update the documentation as well. Moreover, I need to check the backward compatibility and decide on a version increment. Would you kindly change the target to your pull request to the feature branch `chutzpah-settings-file` that I just created? Once I have completed the above-mentioned things, I will merge it with master and release immediately. It should not more than a day or two. Thank you so much for your support so far, I really appreciate it.

**Comment by irega** [comment]
Of course, I have updated the target branch. Let me know if you need help with tests or documentation. Thanks a lot!

**Comment by zpbappi** [comment]
@irega v1.4.0 is published along with your changes. Please feel free to close this issue if it has solved its purpose. Thank you very much for reporting and implementing this feature.

**Comment by irega** [comment]
Thanks @zpbappi , closing the issue :)
